### ISSUE TITLE
classification error

### ISSUE THREAD

**Issue by Sam7791** [lrsoenksen/SPL_UD_DL#4]
Hello,
Congrat for this excellent paper!
image 3_NSPL_0001.png given as an example is classified as a Melanoma using the VGG16 even the light color.
However, the activation map indicates a class 3.
Do you have any explanation?
Thank you very much

**Comment by lrsoenksen** [comment]
Hi Sam7791, thanks for pointing this to us!
Indeed, we put some of those image examples to evince a range of behaviors in the models we trained... some good and some not that great. On bulk though (with many more images), the models should perform close to the ROC curves we report in the paper.  Since we may have some degree of overfitting, that itself may explain the odd behavior between the calculated class probabilities and the activation maps. Sometimes we've seen edge cases or overfitting causing a similar behavior with other moles that are lighter than their respective backgrounds, which are less common (and therefore probably underrepresented) than dark spots in the dataset. There may also be a typo or error in the code that calculates the activation maps or the class selection in one of the several sample codes we uploaded (we will check and fix ASAP if we find an error, or if you find it please let us know to inspect it and fix ) Cheers!
