### ISSUE TITLE
link to dataset is invalid

### ISSUE THREAD

**Issue by weilunhuang-jhu** [lrsoenksen/SPL_UD_DL#6]
Hi, thank you very much for sharing the great work! Could you please check the link to the dataset? It is currently not working. Thank you.

**Comment by lrsoenksen** [comment]
Hi weilunhuang-jhu,

Due to a large number of download requests on the previous dataset links we had on the git, our group has had to reduce it and ask people to request the dataset directly to soenksen@mit.edu. Please do send an email to this address with your Name, Organization, Position, and Anticipated project aims. We will respond rapidly to these requests and secure links to download the database.  we have out  we are now receiving direct requests
